# Question 1. Determine if this matrix is singular or nonsingular.

[[-8, 4, 0, 6],

[7, 5, -7, -9],

[9, 6, 0, -3],

[-8, -1, 4, 2]]

In [1]:
import numpy as np


A = np.array([[-8, 4, 0, 6],
              [7, 5, -7, -9],
              [9, 6, 0, -3],
              [-8, -1, 4, 2]])

# determinant
det_A = np.linalg.det(A)

print(f"Determinant: {det_A}")
print(f"Matrix is {'nonsingular' if abs(det_A) > 1e-10 else 'singular'}") # non-zero so ends up being non-singular (non-zero defined by infinitesimal numbers)

Determinant: 3582.0000000000023
Matrix is nonsingular


# Question 2. Find the null space of this matrix by calculating the SVD (using numpy) to find vectors that span the null space. 

[[6, 0, 6, 4],

[5, -1, 5, 2],

[-4, 2, -4, 0],

[-2, -2, -2, -4]]

In [2]:

B = np.array([[6, 0, 6, 4],
              [5, -1, 5, 2],
              [-4, 2, -4, 0],
              [-2, -2, -2, -4]])

# SVD
U, S, Vt = np.linalg.svd(B)

# null space vectors are the columns of Vt corresponding to zero singular values
print("Singular values:", S)

# columns of Vt where singular values are (approximately) zero
zero = 1e-10
null_space_basis = Vt[np.abs(S) < zero]

print("\nNull space basis vectors:")
for i, vector in enumerate(null_space_basis):
    print(f"vector{i+1}: {vector}")

Singular values: [1.36421779e+01 4.57066528e+00 3.28358591e-16 1.15330835e-16]

Null space basis vectors:
vector1: [-0.73282811 -0.20215513  0.63175054  0.15161635]
vector2: [-4.29121866e-06 -7.42782536e-01 -3.71386977e-01  5.57086902e-01]


# Question 2 (Beezer p.80) 

In [3]:
import numpy as np

# vectors as columns of a matrix
A = np.array([
    [1,  2, -1],
    [3,  0,  3],
    [-1, 4, -5]
])

# vector
b = np.array([1, -9, 11])

# least squares for coefficients 
x, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)

print("Solution (a, b, c):", x)
print("Residuals:", residuals)
print("Rank of A:", rank)
print("Singular values:", s)

# Sigular value of 0 (approximately) and rank of 2 lets us conclude that the system has infinitely many solutions (No linear combination of the vectors in S that equals the target vector since its not found anywhere within the subspace of the 3 linearly dependent vectors)


Solution (a, b, c): [-1.33333333  0.33333333 -1.66666667]
Residuals: []
Rank of A: 2
Singular values: [7.34846923e+00 3.46410162e+00 2.50814447e-16]


# C40 (Beezer p.80)

Find the vector form of the solutions to the system of equations below.

2x1−4x2 + 3x3 + x5 = 6

x1−2x2−2x3 + 14x4−4x5 = 15

x1−2x2 + x3 + 2x4 + x5 = −1

−2x1 + 4x2−12x4 + x5 = −7

In [4]:
import numpy as np

# matrix
A = np.array([
    [2, -4, 3, 0, 1],
    [1, -2, -2, 14, -4],
    [1, -2, 1, 2, 1],
    [-2, 4, 0, -12, 1]
])

# right side
b = np.array([6, 15, -1, -7])

# least squares (finds one solution with first element)
solution = np.linalg.lstsq(A, b, rcond=None)[0]

# null space using SVD
U, S, Vt = np.linalg.svd(A)
null_space = Vt[2:]  # keep only the zero singular value rows

print("Solution:")
print(solution)

print("\nNull Space Basis (free variables):")
for vector in null_space:
    print(vector)

print(f"\nVector Form:")
print("x =", solution, "+ c1 *", null_space[0], "+ c2 *", null_space[1])

Solution:
[ 0.73553719 -1.47107438  1.21487603 -0.44628099 -5.        ]

Null Space Basis (free variables):
[-0.10598125  0.2119625  -0.21479492  0.22329221  0.92078423]
[-8.45819822e-01 -5.17415345e-01 -1.26007245e-01 -3.15018112e-02
  1.58002460e-15]
[-3.79595786e-01  4.12671649e-01  8.03292723e-01  2.00823181e-01
 -3.35857940e-16]

Vector Form:
x = [ 0.73553719 -1.47107438  1.21487603 -0.44628099 -5.        ] + c1 * [-0.10598125  0.2119625  -0.21479492  0.22329221  0.92078423] + c2 * [-8.45819822e-01 -5.17415345e-01 -1.26007245e-01 -3.15018112e-02
  1.58002460e-15]


# Question 1 (Beezer p.91)

In [5]:
import numpy as np

# vectors
vector1 = np.array([1, 2, -1])
vector2 = np.array([3, -4, 2])
vector3 = np.array([4, -2, 1])

# target vector
b = np.array([-1, 8, -4])

# create matrix A with vectors as columns
A = np.column_stack([vector1, vector2, vector3])

print("Matrix A (vectors as columns):")
print(A)
print(f"\nTarget vector b: {b}")

# check if b is in the column space of A
# system Ax = b
try:
    coefficients = np.linalg.solve(A, b)
    print(f"\nCoefficients: {coefficients}")
    print("Yes, target vector is in W")
    
    # verification
    result = coefficients[0] * vector1 + coefficients[1] * vector2 + coefficients[2] * vector3
    print(f"Verify: {coefficients[0]}*vector1 + {coefficients[1]}*vector2 + {coefficients[2]}*vector3 = {result}")
    print(f"Matches target vector: {np.allclose(result, b)}") # check
    
except np.linalg.LinAlgError: # throw error and message if can't solve (matrix is singular)
    print("\nCannot solve directly so checking rank instead")
    
    # check if rank of A equals rank of new matrix
    rank_A = np.linalg.matrix_rank(A)
    A2 = np.column_stack([A, b])
    rank_A2 = np.linalg.matrix_rank(A2)
    
    print(f"Rank of A: {rank_A}")
    print(f"Rank of [A|b]: {rank_A2}")
    
    if rank_A == rank_A2:
        print("Yes, target vector is in W")
     
        coefficients = np.linalg.lstsq(A, b, rcond=None)[0] # coefficients using least squares (-2, -1, 0)
        print(f"Coefficients: {coefficients}")
    else:
        print("No, target vector is not in W")

Matrix A (vectors as columns):
[[ 1  3  4]
 [ 2 -4 -2]
 [-1  2  1]]

Target vector b: [-1  8 -4]

Cannot solve directly so checking rank instead
Rank of A: 2
Rank of [A|b]: 2
Yes, target vector is in W
Coefficients: [ 1.66666667 -1.33333333  0.33333333]


 # C60 (Beezer p.91)

 

In [6]:
import numpy as np


A = np.array([
    [1, 1, 6, -8],
    [1, -2, 0, 1], 
    [-2, 1, -6, 7]
])

print("Matrix A:")
print(A)

# null space using SVD
U, S, Vt = np.linalg.svd(A)

print(f"\nSingular values: {S}")

# rank (number of non-zero singular values)
rank = np.sum(S > 1e-10) # value greater than an approximate zero
print(f"Rank of A: {rank}")

# null space vectors (rows of Vt corresponding to zero singular values)
null_space_basis = Vt[rank:]

print(f"\nNull space basis vectors:")
for i, vector in enumerate(null_space_basis):
    print(f"vector{i+1} = {vector}")

# check to make sure they're in null space
print(f"\nVerification:")
for i, vector in enumerate(null_space_basis):
    result = A @ vector
    print(f"A * vector{i+1} = {result} (should be near zero: {np.allclose(result, np.zeros(3))})") # check result for numerics close to vector of zeros (returns troe if so) --> allclose for rounding errors with very small decimals close to zero being returned in result

Matrix A:
[[ 1  1  6 -8]
 [ 1 -2  0  1]
 [-2  1 -6  7]]

Singular values: [1.37694594e+01 2.89861808e+00 3.14814648e-16]
Rank of A: 2

Null space basis vectors:
vector1 = [-0.66469042 -0.14634364  0.63117655  0.37200315]
vector2 = [0.56647904 0.51644858 0.44140288 0.46641811]

Verification:
A * vector1 = [ 0.00000000e+00 -6.66133815e-16  4.44089210e-16] (should be near zero: True)
A * vector2 = [-8.88178420e-16  1.11022302e-16  0.00000000e+00] (should be near zero: True)
