# C10 (Beezer p.132)

In [15]:
import numpy as np

# matrices
A = np.array([[1, 4, -3],
              [6, 3, 0]])

B = np.array([[3, 2, 1],
              [-2, -6, 5]])

C = np.array([[2, 4],
              [4, 0],
              [-2, 2]])


alpha = 4
beta = 1/2

# (1) A + B
calculation_1 = A + B

# (2) A + C, not possible and will produce error since you physically can't add matrices of different dimensions (sizes, 2 x 3 + 3 x 2)

# (3) B^t + C
calculation_3 = B.T + C 

# (4) A + B^t, not possible and will produce error since you physically can't add matrices of different dimensions (sizes, 2 x 3 + 3 x 2)


# (5) βC
calculation_5 = beta * C

# (6) 4A − 3B
calculation_6 = 4*A - 3*B

# (7) A^t + αC
calculation_7 = A.T + alpha*C

# (8) A + B − C^t
calculation_8 = A + B - C.T

# (9) 4A + 2B − 5C^t
calculation_9 = 4*A + 2*B - 5*C.T

# results
print("(1) A + B =\n", calculation_1)
print("\n(3) B^t + C =\n", calculation_3)
print("\n(5) βC =\n", calculation_5)
print("\n(6) 4A − 3B =\n", calculation_6)
print("\n(7) A^t + αC =\n", calculation_7)
print("\n(8) A + B − C^t =\n", calculation_8)
print("\n(9) 4A + 2B − 5C^t =\n", calculation_9)


(1) A + B =
 [[ 4  6 -2]
 [ 4 -3  5]]

(3) B^t + C =
 [[ 5  2]
 [ 6 -6]
 [-1  7]]

(5) βC =
 [[ 1.  2.]
 [ 2.  0.]
 [-1.  1.]]

(6) 4A − 3B =
 [[ -5  10 -15]
 [ 30  30 -15]]

(7) A^t + αC =
 [[  9  22]
 [ 20   3]
 [-11   8]]

(8) A + B − C^t =
 [[ 2  2  0]
 [ 0 -3  3]]

(9) 4A + 2B − 5C^t =
 [[0 0 0]
 [0 0 0]]


# C20 (Beezer, p.146)

In [ ]:
import numpy as np

# matrices
A = np.array([
    [2, 5],
    [-1, 3],
    [2, -2]
])

B = np.array([
    [1, 5, -3, 4],
    [2, 0, 2, -3]
])
AB = np.dot(A, B)  

AB2 = A @ B

print(AB)
print("\n", AB2)


[[ 12  10   4  -7]
 [  5  -5   9 -13]
 [ -2  10 -10  14]]

 [[ 12  10   4  -7]
 [  5  -5   9 -13]
 [ -2  10 -10  14]]


# C20 (Beezer, p.165)

In [ ]:
import numpy as np


A = np.array([
    [1, 2, 1],
    [0, 1, 1],
    [1, 0, 2]
])

B = np.array([
    [-1, 1, 0],
    [1, 2, 1],
    [0, 1, 1]
])


AB = A @ B   # same as np.dot(A, B)

# determinant and rank
determinant_AB = np.linalg.det(AB)
rank_AB = np.linalg.matrix_rank(AB)

# results
print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nProduct AB:\n", AB)
print("\nDeterminant of AB:", determinant_AB)
print("Rank of AB:", rank_AB)

# verifying AB is nonsingular
if abs(determinant_AB) > 1e-9 and rank_AB == 3: # checking if determinant is greater than zero (statistically accurate zero) and if rank = 3 (checking for full rank usage so that all shown columns are linearly independent, if rank < 3 then that means some column is a linear combination of the others --> singular matrix)
    print("\nAB is nonsingular (invertible).")
    inverse_AB = np.linalg.inv(AB)
    print("\nInverse of AB:\n", inverse_AB) # should work/calculate if nonsingular (invertible/bijective)
else:
    print("\nAB is singular (not invertible).")


Matrix A:
 [[1 2 1]
 [0 1 1]
 [1 0 2]]

Matrix B:
 [[-1  1  0]
 [ 1  2  1]
 [ 0  1  1]]

Product AB:
 [[ 1  6  3]
 [ 1  3  2]
 [-1  3  2]]

Determinant of AB: -6.0
Rank of AB: 3

AB is nonsingular (invertible).

Inverse of AB:
 [[ 4.44089210e-16  5.00000000e-01 -5.00000000e-01]
 [ 6.66666667e-01 -8.33333333e-01 -1.66666667e-01]
 [-1.00000000e+00  1.50000000e+00  5.00000000e-01]]
